# Generated by Django 5.2.6 on 2025-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petproduct',
            name='mrp',
        ),
        migrations.AddField(
            model_name='petproduct',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('ml', 'Millilitre'), ('l', 'Litre'), ('pcs', 'Pieces'), ('inch', 'Inch'), ('pack', 'Pack'), ('other', 'Other')], default='pcs', max_length=20),
        ),
        migrations.AddField(
            model_name='petproduct',
            name='quantity_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='petproduct',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
