# Generated by Django 5.2.6 on 2025-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_petproduct_mrp_petproduct_quantity_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petbanner',
            old_name='image',
            new_name='left_image',
        ),
        migrations.AddField(
            model_name='petbanner',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_banners/'),
        ),
    ]
