# Generated by Django 5.2.6 on 2025-09-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_petproduct_brand_petproduct_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_products/'),
        ),
        migrations.AlterField(
            model_name='petproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
