# Generated by Django 5.2.6 on 2025-09-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_carousalbanner3'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='homecategories/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PetCategory',
        ),
    ]
